spring:
  shardingsphere:
    datasource:
      names: master, slave1, slave2
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/shop?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
      slave2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3308/shop?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
    masterslave:
      name: ds0
      master-data-source-name: master
      slave-data-source-names:
        - slave2
        - slave1
      load-balance-algorithm-type: round_robin
    props:
      sql:
        show: true

# Log Transactions Details
#logging:
#  level:
#    org:
#      springframework:
#        orm:
#          jpa: DEBUG
#        transaction: trace
#      hibernate:
#        engine:
#          transaction:
#            internal:
#              TransactionImpl: debug
#        resource:
#          jdbc: trace
#    com:
#      zaxxer:
#        hikari: DEBUG